name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Set current date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Build Passthrough 
        run: |
          cd passthrough
          pio run
      - name: Archive Passthrough artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DATE }}-passthrough-firmware
          path: |
            passthrough/.pio/build/passthrough/firmware.bin
            passthrough/.pio/build/passthrough/partitions.bin
            passthrough/.pio/build/passthrough/firmware.elf
      - name: Build RC DIY 
        run: |
          cd rc_diy
          pio run
      - name: Archive RC DIY artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DATE }}-rc_diy-firmware
          path: |
            rc_diy/.pio/build/rc_diy/firmware.bin
            rc_diy/.pio/build/passthrough/partitions.bin
            rc_diy/.pio/build/rc_diy/firmware.elf
